### ISSUE TITLE
Trained Weights

### ISSUE THREAD

**Issue by JunbongJang** [Vill-Lab/2024-AAAI-HPT#2]
Thank you for sharing your great work!

When do you plan to share your trained HPT weights? 
Also, which GPU did you use to train and how long was training time?

Thank you again.

**Comment by ThomasWangY** [comment]
We will share our trained HPT weights as soon as possible. 
For implementation details, we trained our model on a single RTX 3090 card. Taking base-to-new generalization as an example, experimenting with three random seeds on all datasets collectively requires no more than 10 hours.
